safer temp file

diff --git a/sshuttle/bin/sudoers-add b/sshuttle/bin/sudoers-add
--- a/sshuttle/bin/sudoers-add
+++ b/sshuttle/bin/sudoers-add
@@ -12,11 +12,13 @@ if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
 	echo "Usage: [content] | $ME sudoers-file-name"
 	echo "This will take a sudoers config validate it and add it to /etc/sudoers.d/{sudoers-file-name}"
 	echo "The config can come from a file, first usage example or piped in second example."
+
 	exit 0
 fi
 
 if [ "$1" == "" ]; then
 	(>&2 echo "This command take at lest one argument. See $ME --help")
+
 	exit 1	
 fi
 
@@ -28,7 +30,8 @@ else
 fi
 
 if [[ $EUID -ne 0 ]]; then
-	echo "This script must be run as root" 
+	echo "This script must be run as root"
+
 	exit 1
 fi
 
@@ -47,20 +50,27 @@ if [ "$FILE_NAME" == "" ]; then
 	exit 1
 fi
 
-touch "/tmp/$FILE_NAME"
+# Make a temp file to hold the sudoers config
+umask 077
+TEMP_FILE=$(mktemp)
+echo "$CONTENT" > "$TEMP_FILE"
 
-echo "$CONTENT" > "/tmp/$FILE_NAME"
+# Make sure the content is valid
+visudo_STDOUT=$(visudo -c -f "$TEMP_FILE" 2>&1)
+visudo_code=$?
+# The temp file is no longer needed
+rm "$TEMP_FILE"
 
-visudo_out= visudo -c -f "/tmp/$FILE_NAME"
-
-if [ $? -eq 0 ]; then
-	if [ -e "/etc/sudoers.d/$FILE_NAME" ]; then
-		rm "/etc/sudoers.d/$FILE_NAME"
-	fi
-	mv "/tmp/$FILE_NAME" "/etc/sudoers.d/$FILE_NAME"
+if [ $visudo_code -eq 0 ]; then
+	echo "$CONTENT" > "/etc/sudoers.d/$FILE_NAME"
 	chmod 0440 "/etc/sudoers.d/$FILE_NAME"
+	echo "The sudoers file /etc/sudoers.d/$FILE_NAME has been successfully created!"
+
 	exit 0
 else
-	echo $visudo_out
+	echo "Invalid sudoers config!"
+	echo "$visudo_STDOUT"
+
 	exit 1
 fi
+
